[2023-12-18 14:00:02,610] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-18T13:00:00+00:00 [queued]>
[2023-12-18 14:00:02,659] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: dag_with_python_weather_v01.fill 2023-12-18T13:00:00+00:00 [queued]>
[2023-12-18 14:00:02,661] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2023-12-18 14:00:02,662] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2023-12-18 14:00:02,663] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2023-12-18 14:00:02,690] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): fill> on 2023-12-18T13:00:00+00:00
[2023-12-18 14:00:02,716] {standard_task_runner.py:52} INFO - Started process 33310 to run task
[2023-12-18 14:00:02,726] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_weather_v01', 'fill', '2023-12-18T13:00:00+00:00', '--job-id', '152', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_weather.py', '--cfg-path', '/tmp/tmp7us0ap55', '--error-file', '/tmp/tmpqzvycpxu']
[2023-12-18 14:00:02,734] {standard_task_runner.py:77} INFO - Job 152: Subtask fill
[2023-12-18 14:00:02,811] {logging_mixin.py:104} INFO - Running <TaskInstance: dag_with_python_weather_v01.fill 2023-12-18T13:00:00+00:00 [running]> on host 5f3722f1fc3b
[2023-12-18 14:00:03,351] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=ggoni
AIRFLOW_CTX_DAG_ID=dag_with_python_weather_v01
AIRFLOW_CTX_TASK_ID=fill
AIRFLOW_CTX_EXECUTION_DATE=2023-12-18T13:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-12-18T13:00:00+00:00
[2023-12-18 14:00:06,097] {python.py:118} INFO - Done. Returned value was: None
[2023-12-18 14:00:06,128] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=dag_with_python_weather_v01, task_id=fill, execution_date=20231218T130000, start_date=20231218T140002, end_date=20231218T140006
[2023-12-18 14:00:06,171] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-12-18 14:00:06,218] {local_task_job.py:146} INFO - Task exited with return code 0
